language: node_js
node_js:
- 0.10
before_script:
  - "npm i -g jasmine-node"
deploy:
  provider: heroku
  api_key:
    secure: YpOvxKY3uPTAkWZ4Xq9LQGMniMGmQ08Th/g2kclX84rYc2Kb/pWW5DzmlNK6Dh3PgD3PZIdphcxke0cZT47PqwqvRg1ipy6uAH7nWqIGRYECBkb6DL3bIzBvIw1Bso0u7XOko4DL6DQf6DXuGaaTzmPN3j4g97/TBmGCuKUh2U8=
  app: iosr-node
  on:
    repo: agh-team/iosr-node
  strategy: api
